___
# Numpy 연습
---

- 1. ndarray 생성
- 2. 변형하기
- 3. 연산
- 4. 함수
- 5. 인덱싱, 슬라이싱

In [3]:
import numpy as np

***
### 1. ndarray 생성
***

In [39]:
arr1 = np.ndarray([3, 6])              # ndarray 만듬. shape 를 인자로 받음
arr2 = np.array([[3, 2], [3, 1]])       # elements 를 인자로 받음
arr3 = np.arange(24)                  # 1 차원 array 를 만듬. 인자만큼 순서대로 늘어트림
arr3_2 = np.arange(3, 10, 2)          # 1차원 array, spacing
arr4 = np.zeros([3, 5])                # 0으로 채운 ndarray 만듬. shape 를 인자도 받음
arr5 = np.empty([3, 6])                # = np.ndarray
arr6 = np.linspace(2, 5, 10)          # 1차원 array 생성. 마지막 인자로서 원소 갯수 지정

print("- arr1 - : \n {}\n".format(arr1))
print("- arr2 - : \n {}\n".format(arr2))
print("- arr3 - : \n {}\n".format(arr3))
print("- arr3_2 - : \n {}\n".format(arr3_2))
print("- arr4 - : \n {}\n".format(arr4))
print("- arr5 - : \n {}\n".format(arr5))
print("- arr6 - : \n {}\n".format(arr6))

- arr1 - : 
 [[1.89146896e-307 1.37961302e-306 6.23053614e-307 6.23053954e-307
  9.34609790e-307 8.45593934e-307]
 [9.34600963e-307 1.86921143e-306 6.23061763e-307 9.34608432e-307
  7.56599128e-307 8.45559303e-307]
 [8.06612616e-308 6.89810244e-307 1.22387550e-307 2.22522596e-306
  8.34423917e-308 9.79107193e-307]]

- arr2 - : 
 [[3 2]
 [3 1]]

- arr3 - : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

- arr3_2 - : 
 [3 5 7 9]

- arr4 - : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

- arr5 - : 
 [[1.89146896e-307 1.37961302e-306 6.23053614e-307 6.23053954e-307
  9.34609790e-307 8.45593934e-307]
 [9.34600963e-307 1.86921143e-306 6.23061763e-307 9.34608432e-307
  7.56599128e-307 8.45559303e-307]
 [8.06612616e-308 6.89810244e-307 1.22387550e-307 2.22522596e-306
  8.34423917e-308 9.79107193e-307]]

- arr6 - : 
 [2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]



---
### 2. 변형하기

---

In [194]:
re_arr3 = arr3.reshape(2,4,-1)      # -1 은 나머지는 알아서 계산하는 인텔리센스

print("- reshape : \n {}\n".format(re_arr3))
print("- flatten : \n {}\n".format(re_arr3.ravel()))    # 완전 1 차원으로 풀기

va_1 = np.ceil(np.ndarray([3, 3]))
va_2 = np.ceil(np.ndarray([3, 3]))

print("- vstack : \n {}\n".format(np.vstack((va_1, va_2))))
print("- hstack : \n {}\n".format(np.hstack((va_1, va_2))))


- reshape : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

- flatten : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

- vstack : 
 [[0. 0. 0.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

- hstack : 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 1. 1. 1. 0. 0.]]



---
### 3. 연산

---

In [219]:
a = np.array([[4, 2], [1, 2]])
b = np.array([[6, 2], [9, 5]])

print("- sum : \n {}\n".format(a + b))          # 원소끼리 합
print("- mul : \n {}\n".format(a * b))          # 원소끼리 곱
print("- matmul : \n {}\n".format(a @ b))       # matrix 곱
print("- basic cal : \n {}\n".format(a >= b))   # |, ^, &, ==, 등 모든 기본 연산 지원. boolean 타입으로 리턴

a *= b                                      
print("- operator : \n {} \n".format(a))        # 증감연산자 적용

- sum : 
 [[10  4]
 [10  7]]

- mul : 
 [[24  4]
 [ 9 10]]

- matmul : 
 [[42 18]
 [24 12]]

- basic cal : 
 [[False  True]
 [False False]]

- operator : 
 [[24  4]
 [ 9 10]] 



---
### 4. 함수

---

In [163]:
arr = np.array([[3, 2, 6], [0, 7, 6]])

print("- min : {}\n".format(arr.min()))                   # ndarray 내 모든 원소 중 최소
print("- max : {}\n".format(arr.max()))                   # ndarray 내 모든 원소 중 최대
print("- min with axis : {}\n".format(arr.min(axis=1)))   # row 별 최소 값. axis 0 이면 column
print("- accum sum : \n {}\n".format(arr.cumsum(axis=1))) # column 별로 원소 순차적으로 더함. 인자가 없으면 0,0 부터 끝까지 더함
print("- transpose : \n {}\n".format(arr.T))              # Transpose

- min : 0

- max : 7

- min with axis : [2 0]

- accum sum : 
 [[ 3  5 11]
 [ 0  7 13]]

- transpose : 
 [[3 0]
 [2 7]
 [6 6]]



---
### 5. 인덱싱, 슬라이싱

---

In [171]:
arr = np.arange(15)

print("- original : {}\n".format(arr))                  # 원본 ndarray
print("- element indexing : {}\n".format(arr[3]))       # 원소 하나 인덱싱
print("- slicing : {}\n".format(arr[3:6]))     # 슬라이싱. 파이썬 문법과 동일
print("- jumping indexing : {}\n".format(arr[-1:0:-2])) # 점핑하며 인덱싱. -는 뒤에서부터 인덱스. 역으로 인덱싱 가능

mularr = np.arange(20).reshape(4, -5)

print("- original : \n {}\n".format(mularr))            # 다차원 ndarray 원본
print("- slicing : \n {}\n".format(mularr[2:4, :3]))    # 다차원 슬라이싱

print("- row iteration :")            # 행 기준으로 iteration
for row in mularr:
    print(row)
    
print("- element iteration")          # 모든 원소 iteration
for element in mularr.flat:
    print(element)


- original : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

- element indexing : 3

- slicing : [3 4 5]

- jumping indexing : [14 12 10  8  6  4  2]

- original : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

- slicing : 
 [[10 11 12]
 [15 16 17]]

- row iteration :
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
