---
# Spatial Pooler & Encoder 통합 테스트 및 시각화

- encoding data sparsity - 25 % 
- overlap threshold      - 20 %
- input range            - 0~30
- epoch                  - 15 

---
- 목표 active duty - 2%
- 목표 sparsity - 2%
---
가까운 입력일수록 SDR 을 일정비율 공유한다.</br>
range 가 넓을수록 유사도 측정하기가 편리함

---

In [1]:
import numpy as np
import random
import time

import nbimporter
import SP3
import Encoder

Importing Jupyter notebook from SP3.ipynb


In [11]:
encoder = Encoder.ScalarEncoder(out_size=100, max_val=30, w=25)
sp = SP3.SpatialPooler(encoder.out_size, columns=512, perm_conn=.6, minOver=encoder.w/5, potential_rate=0.8)

In [14]:
for epoch in range(4):
    for dat in range(30):
        sp.compute_SDR(encoder.encode(dat), debug=True)

In [15]:
sp.viz_sparsity_period()

Loading BokehJS ...

In [16]:
sp.viz_NetState()

Loading BokehJS ...

> desired active column count : 10 <



boost factor

-> 평균 : 1.176318359375, 표준편차 : 0.33743412293243746



active duty

-> 평균 : 0.023701171875000003, 표준편차 : 0.016151218951729586



overlap duty

-> 평균 : 0.892333984375, 표준편차 : 0.14683434203656942



In [17]:
sp.consistency(encoder.encode(5), 10)

오류 : 0.0


In [18]:
sp.compute_SDR(encoder.encode(16), False)
sdr1 = sp.getActiveColumns()
sp.compute_SDR(encoder.encode(17), False)
sdr2 = sp.getActiveColumns()

sp.similarity(sdr1, sdr2)

Loading BokehJS ...

유사도 : 0.2
[  8  10 138 182 315 346 347 352 364 415]
[ 10  54 184 194 226 306 319 343 415 503]


In [19]:
for i in range(30):
    sp.compute_SDR(encoder.encode(i), learn=False)
    sdr1 = sp.getActiveColumns()
    sp.compute_SDR(encoder.encode(i+1), learn=False)
    sdr2 = sp.getActiveColumns()
    
    sp.similarity(sdr1, sdr2, True)
    print('')

Loading BokehJS ...

유사도 : 0.5454545454545454
[ 56  73 127 139 173 180 194 325 383 386 415]
[ 73 104 127 173 175 189 325 383 406 415]



Loading BokehJS ...

유사도 : 0.5
[ 73 104 127 173 175 189 325 383 406 415]
[ 53  58  73  81 104 126 144 173 227 283 325 326 365 383 508]



Loading BokehJS ...

유사도 : 0.7333333333333333
[ 53  58  73  81 104 126 144 173 227 283 325 326 365 383 508]
[ 53  56  58  73  81  88 104 126 242 281 283 313 325 351 365 383 508]



Loading BokehJS ...

유사도 : 0.4117647058823529
[ 53  56  58  73  81  88 104 126 242 281 283 313 325 351 365 383 508]
[ 58  81 104 122 126 256 281 301 383 388 420 470 508]



Loading BokehJS ...

유사도 : 0.9230769230769231
[ 58  81 104 122 126 256 281 301 383 388 420 470 508]
[ 41  58  81  97 104 122 126 144 227 253 256 281 288 299 301 328 383 388
 397 470 508]



Loading BokehJS ...

유사도 : 0.5714285714285714
[ 41  58  81  97 104 122 126 144 227 253 256 281 288 299 301 328 383 388
 397 470 508]
[ 81 104 115 126 173 253 256 281 283 299 328 376 383 397 410 470 508]



Loading BokehJS ...

유사도 : 0.5882352941176471
[ 81 104 115 126 173 253 256 281 283 299 328 376 383 397 410 470 508]
[ 79  81 104 126 189 202 281 283 328 383 397 410 508]



Loading BokehJS ...

유사도 : 0.5384615384615384
[ 79  81 104 126 189 202 281 283 328 383 397 410 508]
[ 60  81 125 166 202 281 325 328 365 397 410 508]



Loading BokehJS ...

유사도 : 0.75
[ 60  81 125 166 202 281 325 328 365 397 410 508]
[ 36  70  81 125 281 325 328 365 397 410 439 508]



Loading BokehJS ...

유사도 : 0.6666666666666666
[ 36  70  81 125 281 325 328 365 397 410 439 508]
[ 36  81 112 125 281 325 328 336 439 508]



Loading BokehJS ...

유사도 : 0.9
[ 36  81 112 125 281 325 328 336 439 508]
[ 36  81 112 125 261 281 325 336 339 439 508]



Loading BokehJS ...

유사도 : 0.45454545454545453
[ 36  81 112 125 261 281 325 336 339 439 508]
[  0  81  83 225 281 314 325 339 472 508]



Loading BokehJS ...

유사도 : 0.6
[  0  81  83 225 281 314 325 339 472 508]
[ 81 225 269 281 314 325 404 413 438 472]



Loading BokehJS ...

유사도 : 0.2
[ 81 225 269 281 314 325 404 413 438 472]
[  0   6   8 108 156 158 176 195 314 346 371 472]



Loading BokehJS ...

유사도 : 0.16666666666666666
[  0   6   8 108 156 158 176 195 314 346 371 472]
[  0   8  83 114 135 352 364 366 395 415]



Loading BokehJS ...

유사도 : 0.4
[  0   8  83 114 135 352 364 366 395 415]
[  8  10 138 182 315 346 347 352 364 415]



Loading BokehJS ...

유사도 : 0.2
[  8  10 138 182 315 346 347 352 364 415]
[ 10  54 184 194 226 306 319 343 415 503]



Loading BokehJS ...

유사도 : 0.5
[ 10  54 184 194 226 306 319 343 415 503]
[ 28  54 184 194 205 206 226 263 333 343]



Loading BokehJS ...

유사도 : 0.3
[ 28  54 184 194 205 206 226 263 333 343]
[ 28  39  49  83 130 134 158 194 226 275 350]



Loading BokehJS ...

유사도 : 0.36363636363636365
[ 28  39  49  83 130 134 158 194 226 275 350]
[ 31  39  49  83 191 194 203 260 398 460 477]



Loading BokehJS ...

유사도 : 0.2727272727272727
[ 31  39  49  83 191 194 203 260 398 460 477]
[ 65  75  81  85  91 154 171 203 218 219 255 260 274 379 423 455 460 465]



Loading BokehJS ...

유사도 : 0.3888888888888889
[ 65  75  81  85  91 154 171 203 218 219 255 260 274 379 423 455 460 465]
[ 49  70  81  85  91 171 199 219 260 379 437]



Loading BokehJS ...

유사도 : 0.36363636363636365
[ 49  70  81  85  91 171 199 219 260 379 437]
[ 49  53  81 171 194 199 205 257 265 307 334 381 391 427 461 508]



Loading BokehJS ...

유사도 : 0.3125
[ 49  53  81 171 194 199 205 257 265 307 334 381 391 427 461 508]
[ 14  21 171 207 213 257 265 334 381 426 432]



Loading BokehJS ...

유사도 : 0.45454545454545453
[ 14  21 171 207 213 257 265 334 381 426 432]
[ 20  53  84 117 148 165 171 181 194 205 249 257 334 360 381 391 394 432]



Loading BokehJS ...

유사도 : 0.2777777777777778
[ 20  53  84 117 148 165 171 181 194 205 249 257 334 360 381 391 394 432]
[ 14  21 117 169 171 207 257 265 381 426 432]



Loading BokehJS ...

유사도 : 0.36363636363636365
[ 14  21 117 169 171 207 257 265 381 426 432]
[ 49  53  81 171 194 199 205 257 265 307 334 381 391 427 461 508]



Loading BokehJS ...

유사도 : 0.4375
[ 49  53  81 171 194 199 205 257 265 307 334 381 391 427 461 508]
[ 49  70  81  85 171 191 199 202 219 260 307 334 437 508]



Loading BokehJS ...

유사도 : 0.35714285714285715
[ 49  70  81  85 171 191 199 202 219 260 307 334 437 508]
[ 65  75  81  85  91 154 171 203 218 219 255 260 274 379 423 455 460 465]



Loading BokehJS ...

유사도 : 0.3333333333333333
[ 65  75  81  85  91 154 171 203 218 219 255 260 274 379 423 455 460 465]
[ 81  85 191 194 203 260 398 423 460 477 508]

