---
# Spatial Pooler & Encoder 통합 테스트 및 시각화

- encoding data sparsity - 25 % 
- overlap threshold      - 20 %
- input range            - 0~30
- epoch                  - 15 

---
가까운 입력일수록 SDR 을 일정비율 공유한다.</br>
range 가 넓을수록 유사도 측정하기가 편리함

---

In [1]:
import numpy as np
import random
import time

import nbimporter
import SP3
import Encoder

In [35]:
encoder = Encoder.ScalarEncoder(out_size=100, max_val=30, w=25)
sp = SP3.SpatialPooler(encoder.out_size, columns=512, perm_conn=.6, minOver=encoder.w/5, potential_rate=0.8)

In [36]:
for epoch in range(5):
    for dat in range(30):
        sp.compute_SDR(encoder.encode(dat), debug=True)

In [37]:
sp.viz_sparsity_period()

Loading BokehJS ...

In [39]:
sp.viz_NetState()

Loading BokehJS ...

> desired active column count : 10 <



boost factor

-> 평균 : 1.0526041666666668, 표준편차 : 0.2390613652841625



active duty

-> 평균 : 0.026250000000000002, 표준편차 : 0.016051133570215183



overlap duty

-> 평균 : 0.9025911458333333, 표준편차 : 0.14238959365043874



In [40]:
sp.consistency(encoder.encode(5), 10)

오류 : 0.0


In [45]:
sp.compute_SDR(encoder.encode(16), False)
sdr1 = sp.getActiveColumns()
sp.compute_SDR(encoder.encode(17), False)
sdr2 = sp.getActiveColumns()

sp.similarity(sdr1, sdr2)

Loading BokehJS ...

유사도 : 0.09090909090909091
[ 17  26  89 114 246 388 414 421 466 475 496]
[ 11  31 131 278 282 309 375 380 381 396 414 504]


In [44]:
for i in range(30):
    sp.compute_SDR(encoder.encode(i), learn=False)
    sdr1 = sp.getActiveColumns()
    sp.compute_SDR(encoder.encode(i+1), learn=False)
    sdr2 = sp.getActiveColumns()
    
    sp.similarity(sdr1, sdr2, True)
    print('')

Loading BokehJS ...

유사도 : 0.625
[ 59  78 133 139 148 149 188 334 367 397 408 435 436 449 452 475]
[ 59  78 119 148 149 235 281 334 397 435 436 439 449 475 481]



Loading BokehJS ...

유사도 : 0.3333333333333333
[ 59  78 119 148 149 235 281 334 397 435 436 439 449 475 481]
[ 48  65  78 149 187 196 235 393 397 432 481]



Loading BokehJS ...

유사도 : 0.45454545454545453
[ 48  65  78 149 187 196 235 393 397 432 481]
[ 65 149 173 196 246 284 292 308 367 429 432 452 481]



Loading BokehJS ...

유사도 : 0.23076923076923078
[ 65 149 173 196 246 284 292 308 367 429 432 452 481]
[112 129 136 148 158 213 246 308 377 452 499]



Loading BokehJS ...

유사도 : 0.45454545454545453
[112 129 136 148 158 213 246 308 377 452 499]
[ 52  79  93 112 136 196 317 343 377 452 494 499 503 505 510]



Loading BokehJS ...

유사도 : 0.5333333333333333
[ 52  79  93 112 136 196 317 343 377 452 494 499 503 505 510]
[ 52  79  93 115 143 161 191 377 424 443 499 503 505 510]



Loading BokehJS ...

유사도 : 0.7857142857142857
[ 52  79  93 115 143 161 191 377 424 443 499 503 505 510]
[ 52  93 115 137 143 161 191 377 425 499 503 505 510]



Loading BokehJS ...

유사도 : 0.15384615384615385
[ 52  93 115 137 143 161 191 377 425 499 503 505 510]
[  1  48 137 143 176 220 246 314 367 496]



Loading BokehJS ...

유사도 : 0.6
[  1  48 137 143 176 220 246 314 367 496]
[  1  81  93  94 137 143 161 176 235 246 314 343 417]



Loading BokehJS ...

유사도 : 0.38461538461538464
[  1  81  93  94 137 143 161 176 235 246 314 343 417]
[ 69  81  94 236 246 277 307 314 377 417 422]



Loading BokehJS ...

유사도 : 0.2727272727272727
[ 69  81  94 236 246 277 307 314 377 417 422]
[105 161 172 186 195 202 314 409 417 422]



Loading BokehJS ...

유사도 : 0.7
[105 161 172 186 195 202 314 409 417 422]
[  1 126 161 172 179 186 195 202 314 346 422]



Loading BokehJS ...

유사도 : 0.2727272727272727
[  1 126 161 172 179 186 195 202 314 346 422]
[ 22  35  69 126 161 172 310 366 377 410 496]



Loading BokehJS ...

유사도 : 0.36363636363636365
[ 22  35  69 126 161 172 310 366 377 410 496]
[ 11  79 202 217 282 310 322 366 377 388 412 414 425 496]



Loading BokehJS ...

유사도 : 0.14285714285714285
[ 11  79 202 217 282 310 322 366 377 388 412 414 425 496]
[ 26  89 114 203 246 269 366 414 421 466]



Loading BokehJS ...

유사도 : 0.7
[ 26  89 114 203 246 269 366 414 421 466]
[ 17  26  89 114 246 388 414 421 466 475 496]



Loading BokehJS ...

유사도 : 0.09090909090909091
[ 17  26  89 114 246 388 414 421 466 475 496]
[ 11  31 131 278 282 309 375 380 381 396 414 504]



Loading BokehJS ...

유사도 : 0.3333333333333333
[ 11  31 131 278 282 309 375 380 381 396 414 504]
[ 23  26  91 168 288 309 321 381 396 504]



Loading BokehJS ...

유사도 : 0.4
[ 23  26  91 168 288 309 321 381 396 504]
[ 72  91 127 182 288 353 381 396 423 426]



Loading BokehJS ...

유사도 : 0.2
[ 72  91 127 182 288 353 381 396 423 426]
[ 34  66 126 147 175 201 243 247 249 343 381 409 423]



Loading BokehJS ...

유사도 : 0.23076923076923078
[ 34  66 126 147 175 201 243 247 249 343 381 409 423]
[ 91 198 242 247 249 251 290 379 423 462 502]



Loading BokehJS ...

유사도 : 0.2727272727272727
[ 91 198 242 247 249 251 290 379 423 462 502]
[  5  74 156 198 293 332 360 379 447 462]



Loading BokehJS ...

유사도 : 0.3
[  5  74 156 198 293 332 360 379 447 462]
[  7 135 156 227 299 355 379 385 426 447]



Loading BokehJS ...

유사도 : 0.6
[  7 135 156 227 299 355 379 385 426 447]
[  7  45  72 156 227 295 299 301 324 351 376 379 385]



Loading BokehJS ...

유사도 : 0.5384615384615384
[  7  45  72 156 227 295 299 301 324 351 376 379 385]
[  7  25  45  72 145 156 170 324 379 385]



Loading BokehJS ...

유사도 : 0.7
[  7  25  45  72 145 156 170 324 379 385]
[  7  45  72 156 227 295 299 301 324 344 351 376 379 385]



Loading BokehJS ...

유사도 : 0.42857142857142855
[  7  45  72 156 227 295 299 301 324 344 351 376 379 385]
[  7 135 156 227 299 355 379 385 426 447]



Loading BokehJS ...

유사도 : 0.3
[  7 135 156 227 299 355 379 385 426 447]
[  5  74 156 198 247 293 360 379 411 447]



Loading BokehJS ...

유사도 : 0.3
[  5  74 156 198 247 293 360 379 411 447]
[ 91 198 242 247 249 251 290 379 423 462 502]



Loading BokehJS ...

유사도 : 0.5454545454545454
[ 91 198 242 247 249 251 290 379 423 462 502]
[ 91 126 168 201 247 249 343 379 381 409 423 502]

