---
# Spatial Pooler & Encoder 통합 테스트 및 시각화

- encoding data sparsity - 25 % 
- overlap threshold      - 20 %
- input range            - 0~30
- epoch                  - 15 

---
가까운 입력일수록 SDR 을 일정비율 공유한다.</br>
range 가 넓을수록 유사도 측정하기가 편리함

---

In [1]:
import numpy as np
import random
import time

import nbimporter
import SP3
import Encoder

Importing Jupyter notebook from SP3.ipynb
Importing Jupyter notebook from Encoder.ipynb


In [2]:
encoder = Encoder.ScalarEncoder(out_size=100, max_val=30, w=25)
sp = SP3.SpatialPooler(encoder.out_size, columns=512, perm_conn=.6, minOver=encoder.w/5, potential_rate=0.9)

In [6]:
for epoch in range(4):
    for dat in range(30):
        sp.compute_SDR(encoder.encode(dat), debug=False)

In [53]:
sp.viz_sparsity_period()

Loading BokehJS ...

C:\Anaconda\lib\site-packages\bokeh\models\sources.py:110: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 200), ('y', 0)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))


In [ ]:
sp.viz_NetState()

In [55]:
sp.viz_activeCol()

Loading BokehJS ...

active columns : [30, 103, 175, 190, 198, 279, 308, 354, 407, 454] 
count : 10


In [56]:
sp.consistency(encoder.encode(5), 10)

오류 : 0.0


In [157]:
sp.compute_SDR(encoder.encode(15), False)
sdr1 = sp.getActiveColumns()
sp.compute_SDR(encoder.encode(17), False)
sdr2 = sp.getActiveColumns()

sp.similarity(sdr1, sdr2)

Loading BokehJS ...

유사도 : 0.16666666666666666
[29, 49, 95, 106, 163, 173, 200, 295, 339, 395]
[29, 67, 95, 128, 173, 254, 266, 300, 358, 451, 485]


In [4]:
for i in range(30):
    sp.compute_SDR(encoder.encode(i), learn=False)
    sdr1 = sp.getActiveColumns()
    sp.compute_SDR(encoder.encode(i+3), learn=False)
    sdr2 = sp.getActiveColumns()
    
    sp.similarity(sdr1, sdr2, True)
    print('')

Loading BokehJS ...

유사도 : 0.42105263157894735
[ 14  25  51 156 168 171 184 212 245 259 284 288 290 298 301 332 351 431
 445]
[ 14  94 168 171 235 240 259 288 290 301 329 375 431]



Loading BokehJS ...

유사도 : 0.4
[ 14  25  46  51 156 171 227 259 288 290 298 301 329 332 351]
[  1  14  94 171 240 259 288 301 329 378 449]



Loading BokehJS ...

유사도 : 0.4
[ 14  25  97 168 171 227 259 288 290 298 301 329 375 407 431]
[ 57  70  94 171 240 259 288 301 324 329 354 375 449]



Loading BokehJS ...

유사도 : 0.5384615384615384
[ 14  94 168 171 235 240 259 288 290 301 329 375 431]
[ 57  70  94 160 171 240 273 282 288 301 324 329 354 375 423 449]



Loading BokehJS ...

유사도 : 0.45454545454545453
[  1  14  94 171 240 259 288 301 329 378 449]
[ 57 171 240 273 282 288 301 324 329 423]



Loading BokehJS ...

유사도 : 0.5384615384615384
[ 57  70  94 171 240 259 288 301 324 329 354 375 449]
[ 26  57 171 178 273 288 301 329 375 407 423 449]



Loading BokehJS ...

유사도 : 0.625
[ 57  70  94 160 171 240 273 282 288 301 324 329 354 375 423 449]
[  1  13  26  57 129 171 188 273 288 290 301 324 329 357 375 407 423 449]



Loading BokehJS ...

유사도 : 0.6
[ 57 171 240 273 282 288 301 324 329 423]
[ 57  68 140 171 188 288 290 301 329 375 386 423 439]



Loading BokehJS ...

유사도 : 0.5833333333333334
[ 26  57 171 178 273 288 301 329 375 407 423 449]
[ 13  57  68 171 188 230 241 259 288 301 319 329 386 413 423 439 449]



Loading BokehJS ...

유사도 : 0.2222222222222222
[  1  13  26  57 129 171 188 273 288 290 301 324 329 357 375 407 423 449]
[ 27  57  68 168 230 259 301 319 329 386 407 439 443]



Loading BokehJS ...

유사도 : 0.6923076923076923
[ 57  68 140 171 188 288 290 301 329 375 386 423 439]
[ 27  46  51  57  68 103 148 179 184 188 216 230 282 288 290 301 315 329
 375 407 439 443 450 504 506]



Loading BokehJS ...

유사도 : 0.17647058823529413
[ 13  57  68 171 188 230 241 259 288 301 319 329 386 413 423 439 449]
[  5  51  68 184 255 290 301 329 418 450 460]



Loading BokehJS ...

유사도 : 0.6153846153846154
[ 27  57  68 168 230 259 301 319 329 386 407 439 443]
[  5  14  27  51  62  68 115 118 127 152 156 158 168 184 188 240 255 276
 285 296 301 319 329 359 365 371 378 387 401 407 443 445 449 450 465]



Loading BokehJS ...

유사도 : 0.2
[ 27  46  51  57  68 103 148 179 184 188 216 230 282 288 290 301 315 329
 375 407 439 443 450 504 506]
[  5  51 127 168 184 216 296 301 329 365 387 401 449 465]



Loading BokehJS ...

유사도 : 0.36363636363636365
[  5  51  68 184 255 290 301 329 418 450 460]
[ 26  51  62 103 115 118 168 184 203 296 301 329 431 449]



Loading BokehJS ...

유사도 : 0.34285714285714286
[  5  14  27  51  62  68 115 118 127 152 156 158 168 184 188 240 255 276
 285 296 301 319 329 359 365 371 378 387 401 407 443 445 449 450 465]
[ 26  39  51  68 103 118 168 188 216 240 282 296 301 329 425 438 443 445
 449 463]



Loading BokehJS ...

유사도 : 0.42857142857142855
[  5  51 127 168 184 216 296 301 329 365 387 401 449 465]
[ 26  51  68 156 238 282 285 296 301 319 378 401 431 438 446 449 452 463
 465]



Loading BokehJS ...

유사도 : 0.42857142857142855
[ 26  51  62 103 115 118 168 184 203 296 301 329 431 449]
[ 25  26  51 115 156 238 282 301 329 449]



Loading BokehJS ...

유사도 : 0.3
[ 26  39  51  68 103 118 168 188 216 240 282 296 301 329 425 438 443 445
 449 463]
[ 26  51  75 115 156 227 240 282 301 342 370 390 449]



Loading BokehJS ...

유사도 : 0.3157894736842105
[ 26  51  68 156 238 282 285 296 301 319 378 401 431 438 446 449 452 463
 465]
[ 26  51 156 227 282 301 302 342 370 390 449]



Loading BokehJS ...

유사도 : 0.5
[ 25  26  51 115 156 238 282 301 329 449]
[ 26 140 156 227 282 301 320 324 342 354 370 449]



Loading BokehJS ...

유사도 : 0.6153846153846154
[ 26  51  75 115 156 227 240 282 301 342 370 390 449]
[ 26  98 156 227 259 282 288 301 324 342 354 370 441 446 449]



Loading BokehJS ...

유사도 : 0.7272727272727273
[ 26  51 156 227 282 301 302 342 370 390 449]
[ 26  98 127 156 227 259 273 288 301 324 342 354 370 380 390 395 446 449
 486]



Loading BokehJS ...

유사도 : 0.5833333333333334
[ 26 140 156 227 282 301 320 324 342 354 370 449]
[ 26  51  98 127 156 227 259 288 301 342 370 395 446 449 486]



Loading BokehJS ...

유사도 : 0.6666666666666666
[ 26  98 156 227 259 282 288 301 324 342 354 370 441 446 449]
[ 26 140 156 227 282 301 320 324 342 354 370 449]



Loading BokehJS ...

유사도 : 0.42105263157894735
[ 26  98 127 156 227 259 273 288 301 324 342 354 370 380 390 395 446 449
 486]
[ 26  51 115 156 168 227 282 301 310 329 342 370 390 438 449]



Loading BokehJS ...

유사도 : 0.5333333333333333
[ 26  51  98 127 156 227 259 288 301 342 370 395 446 449 486]
[ 26  51  75 115 156 227 240 282 301 342 370 390 449]



Loading BokehJS ...

유사도 : 0.5833333333333334
[ 26 140 156 227 282 301 320 324 342 354 370 449]
[ 26 115 156 240 282 301 324 329 342 438 449]



Loading BokehJS ...

유사도 : 0.6
[ 26  51 115 156 168 227 282 301 310 329 342 370 390 438 449]
[ 26 115 156 240 282 301 324 329 342 438 449]



Loading BokehJS ...

유사도 : 0.6153846153846154
[ 26  51  75 115 156 227 240 282 301 342 370 390 449]
[ 26 115 156 240 282 301 324 329 342 438 449]

